defmodule Mydia.Metadata.NfoWriterTest do
  use ExUnit.Case, async: true

  alias Mydia.Metadata.NfoWriter
  alias Mydia.Metadata.Structs.{MediaMetadata, CastMember, CrewMember, SeasonInfo}

  # Helper to build a MediaItem-like struct for testing
  defp build_media_item(attrs \\ %{}) do
    defaults = %{
      id: "test-id",
      title: "Test Title",
      type: "movie",
      tmdb_id: 12345,
      tvdb_id: nil,
      imdb_id: nil,
      metadata: nil,
      media_files: [],
      episodes: []
    }

    struct(Mydia.Media.MediaItem, Map.merge(defaults, attrs))
  end

  defp build_metadata(attrs \\ %{}) do
    defaults = %{
      provider_id: "12345",
      provider: :metadata_relay,
      media_type: :movie,
      title: "The Matrix",
      original_title: "The Matrix",
      year: 1999,
      overview: "A hacker discovers reality is a simulation.",
      tagline: "Welcome to the Real World.",
      runtime: 136,
      vote_average: 8.7,
      status: nil,
      genres: ["Action", "Science Fiction"],
      imdb_id: "tt0133093",
      cast: [
        CastMember.new(name: "Keanu Reeves", character: "Neo"),
        CastMember.new(name: "Laurence Fishburne", character: "Morpheus")
      ],
      crew: [
        CrewMember.new(name: "Lana Wachowski", job: "Director", department: "Directing"),
        CrewMember.new(name: "Lilly Wachowski", job: "Director", department: "Directing")
      ],
      seasons: nil
    }

    struct(MediaMetadata, Map.merge(defaults, attrs))
  end

  defp build_episode(attrs \\ %{}) do
    defaults = %{
      id: "ep-1",
      season_number: 1,
      episode_number: 1,
      title: "Pilot",
      air_date: ~D[2020-01-15],
      metadata: %Mydia.Metadata.Structs.EpisodeData{
        season_number: 1,
        episode_number: 1,
        name: "Pilot",
        overview: "The first episode.",
        runtime: 45,
        air_date: ~D[2020-01-15]
      }
    }

    struct(Mydia.Media.Episode, Map.merge(defaults, attrs))
  end

  defp build_media_file(attrs \\ %{}) do
    library_path = Map.get(attrs, :library_path, build_library_path())

    defaults = %{
      id: "file-1",
      relative_path: "The Matrix (1999)/The Matrix (1999).mkv",
      library_path_id: library_path.id,
      library_path: library_path,
      episode_id: nil,
      trashed_at: nil
    }

    struct(Mydia.Library.MediaFile, Map.merge(defaults, attrs))
  end

  defp build_library_path(attrs \\ %{}) do
    defaults = %{
      id: "lp-1",
      path: "/media/movies",
      type: :movies,
      write_nfo: true
    }

    struct(Mydia.Settings.LibraryPath, Map.merge(defaults, attrs))
  end

  describe "generate_movie_xml/1" do
    test "generates full movie XML with all fields" do
      metadata = build_metadata()
      media_item = build_media_item(%{tmdb_id: 603, metadata: metadata})
      xml = NfoWriter.generate_movie_xml(media_item)

      assert xml =~ ~s(<?xml version="1.0" encoding="utf-8" standalone="yes"?>)
      assert xml =~ "<!-- Generated by Mydia -->"
      assert xml =~ "<movie>"
      assert xml =~ "<title>The Matrix</title>"
      assert xml =~ "<originaltitle>The Matrix</originaltitle>"
      assert xml =~ "<sorttitle>The Matrix</sorttitle>"
      assert xml =~ "<year>1999</year>"
      assert xml =~ "<rating>8.7</rating>"
      assert xml =~ "<plot>A hacker discovers reality is a simulation.</plot>"
      assert xml =~ "<tagline>Welcome to the Real World.</tagline>"
      assert xml =~ "<runtime>136</runtime>"
      assert xml =~ "<genre>Action</genre>"
      assert xml =~ "<genre>Science Fiction</genre>"
      assert xml =~ ~s(<uniqueid type="tmdb">603</uniqueid>)
      assert xml =~ ~s(<uniqueid type="imdb">tt0133093</uniqueid>)
      assert xml =~ "<name>Keanu Reeves</name>"
      assert xml =~ "<role>Neo</role>"
      assert xml =~ "<director>Lana Wachowski</director>"
      assert xml =~ "<director>Lilly Wachowski</director>"
      assert xml =~ "</movie>"
    end

    test "generates minimal movie XML when metadata is nil" do
      media_item = build_media_item(%{title: "Unknown Movie", metadata: nil})
      xml = NfoWriter.generate_movie_xml(media_item)

      assert xml =~ "<movie>"
      assert xml =~ "<title>Unknown Movie</title>"
      assert xml =~ "</movie>"
      refute xml =~ "<genre>"
      refute xml =~ "<actor>"
    end

    test "handles partial metadata with nil fields" do
      metadata =
        build_metadata(%{
          overview: nil,
          tagline: nil,
          genres: [],
          cast: [],
          crew: []
        })

      media_item = build_media_item(%{metadata: metadata})
      xml = NfoWriter.generate_movie_xml(media_item)

      assert xml =~ "<title>The Matrix</title>"
      refute xml =~ "<plot>"
      refute xml =~ "<tagline>"
      refute xml =~ "<genre>"
      refute xml =~ "<actor>"
      refute xml =~ "<director>"
    end

    test "XML-escapes special characters" do
      metadata =
        build_metadata(%{
          title: "Tom & Jerry",
          overview: "A tale of <cats> and \"mice\" that's fun."
        })

      media_item = build_media_item(%{metadata: metadata})
      xml = NfoWriter.generate_movie_xml(media_item)

      assert xml =~ "<title>Tom &amp; Jerry</title>"
      assert xml =~ "&lt;cats&gt;"
      assert xml =~ "&quot;mice&quot;"
      assert xml =~ "that&apos;s fun."
    end
  end

  describe "generate_tvshow_xml/1" do
    test "generates full TV show XML" do
      metadata =
        build_metadata(%{
          media_type: :tv_show,
          title: "Breaking Bad",
          year: 2008,
          overview: "A chemistry teacher turned drug lord.",
          status: "Ended",
          genres: ["Drama", "Crime"]
        })

      media_item =
        build_media_item(%{
          type: "tv_show",
          tmdb_id: 1396,
          tvdb_id: 81189,
          metadata: metadata
        })

      xml = NfoWriter.generate_tvshow_xml(media_item)

      assert xml =~ "<tvshow>"
      assert xml =~ "<title>Breaking Bad</title>"
      assert xml =~ "<year>2008</year>"
      assert xml =~ "<status>Ended</status>"
      assert xml =~ ~s(<uniqueid type="tmdb">1396</uniqueid>)
      assert xml =~ ~s(<uniqueid type="tvdb">81189</uniqueid>)
      assert xml =~ "</tvshow>"
      # TV shows don't get tagline
      refute xml =~ "<tagline>"
    end

    test "generates minimal TV show XML when metadata is nil" do
      media_item = build_media_item(%{type: "tv_show", title: "Unknown Show", metadata: nil})
      xml = NfoWriter.generate_tvshow_xml(media_item)

      assert xml =~ "<tvshow>"
      assert xml =~ "<title>Unknown Show</title>"
      assert xml =~ "</tvshow>"
    end
  end

  describe "generate_season_xml/2" do
    test "generates season XML with season info" do
      metadata =
        build_metadata(%{
          seasons: [
            %SeasonInfo{season_number: 1, name: "Season 1", overview: "The beginning."},
            %SeasonInfo{season_number: 2, name: "Season 2", overview: "It continues."}
          ]
        })

      media_item = build_media_item(%{metadata: metadata})
      xml = NfoWriter.generate_season_xml(media_item, 1)

      assert xml =~ "<season>"
      assert xml =~ "<title>Season 1</title>"
      assert xml =~ "<seasonnumber>1</seasonnumber>"
      assert xml =~ "<plot>The beginning.</plot>"
      assert xml =~ "</season>"
    end

    test "generates season XML with default title when season info not found" do
      media_item = build_media_item(%{metadata: build_metadata(%{seasons: []})})
      xml = NfoWriter.generate_season_xml(media_item, 3)

      assert xml =~ "<title>Season 3</title>"
      assert xml =~ "<seasonnumber>3</seasonnumber>"
    end

    test "handles nil metadata" do
      media_item = build_media_item(%{metadata: nil})
      xml = NfoWriter.generate_season_xml(media_item, 1)

      assert xml =~ "<title>Season 1</title>"
    end
  end

  describe "generate_episode_xml/2" do
    test "generates full episode XML" do
      metadata = build_metadata(%{media_type: :tv_show, title: "Breaking Bad"})

      media_item =
        build_media_item(%{
          type: "tv_show",
          title: "Breaking Bad",
          tmdb_id: 1396,
          metadata: metadata
        })

      episode =
        build_episode(%{
          season_number: 1,
          episode_number: 1,
          title: "Pilot",
          air_date: ~D[2008-01-20],
          metadata: %Mydia.Metadata.Structs.EpisodeData{
            season_number: 1,
            episode_number: 1,
            name: "Pilot",
            overview: "A chemistry teacher starts a new career.",
            runtime: 58,
            air_date: ~D[2008-01-20]
          }
        })

      xml = NfoWriter.generate_episode_xml(media_item, episode)

      assert xml =~ "<episodedetails>"
      assert xml =~ "<title>Pilot</title>"
      assert xml =~ "<showtitle>Breaking Bad</showtitle>"
      assert xml =~ "<season>1</season>"
      assert xml =~ "<episode>1</episode>"
      assert xml =~ "<aired>2008-01-20</aired>"
      assert xml =~ "<plot>A chemistry teacher starts a new career.</plot>"
      assert xml =~ "<runtime>58</runtime>"
      assert xml =~ ~s(<uniqueid type="tmdb">1396</uniqueid>)
      assert xml =~ "</episodedetails>"
    end

    test "generates episode XML with nil episode metadata" do
      media_item =
        build_media_item(%{type: "tv_show", title: "Show", metadata: build_metadata()})

      episode =
        build_episode(%{
          title: "Episode Title",
          air_date: ~D[2020-06-15],
          metadata: nil
        })

      xml = NfoWriter.generate_episode_xml(media_item, episode)

      assert xml =~ "<title>Episode Title</title>"
      assert xml =~ "<aired>2020-06-15</aired>"
      refute xml =~ "<plot>"
      refute xml =~ "<runtime>"
    end
  end

  describe "write_nfo_file/2" do
    @tag :tmp_dir
    test "writes file atomically", %{tmp_dir: tmp_dir} do
      path = Path.join(tmp_dir, "test.nfo")
      content = "<movie><title>Test</title></movie>"

      assert :ok = NfoWriter.write_nfo_file(path, content)
      assert File.read!(path) == content
      # Ensure no tmp file remains
      refute File.exists?(path <> ".tmp")
    end

    @tag :tmp_dir
    test "overwrites existing file", %{tmp_dir: tmp_dir} do
      path = Path.join(tmp_dir, "test.nfo")
      File.write!(path, "old content")

      assert :ok = NfoWriter.write_nfo_file(path, "new content")
      assert File.read!(path) == "new content"
    end

    test "returns error for invalid path" do
      assert {:error, _reason} =
               NfoWriter.write_nfo_file("/nonexistent/dir/test.nfo", "content")
    end
  end

  describe "derive_show_root/2" do
    test "derives show root with season folder" do
      lp = build_library_path(%{path: "/media/tv"})

      files = [
        build_media_file(%{
          relative_path: "Breaking Bad/Season 01/S01E01.mkv",
          library_path: lp
        })
      ]

      assert NfoWriter.derive_show_root(files, lp) == "/media/tv/Breaking Bad"
    end

    test "derives show root without season folder" do
      lp = build_library_path(%{path: "/media/tv"})

      files = [
        build_media_file(%{
          relative_path: "Short Show/S01E01.mkv",
          library_path: lp
        })
      ]

      assert NfoWriter.derive_show_root(files, lp) == "/media/tv/Short Show"
    end

    test "derives show root with category path" do
      lp = build_library_path(%{path: "/media/tv"})

      files = [
        build_media_file(%{
          relative_path: "Anime/One Punch Man/Season 01/S01E01.mkv",
          library_path: lp
        })
      ]

      assert NfoWriter.derive_show_root(files, lp) == "/media/tv/Anime/One Punch Man"
    end

    test "returns nil for empty files list" do
      lp = build_library_path(%{path: "/media/tv"})
      assert NfoWriter.derive_show_root([], lp) == nil
    end
  end

  describe "detect_season_folders/2" do
    test "detects season folders from media files" do
      lp = build_library_path(%{path: "/media/tv"})

      files = [
        build_media_file(%{
          relative_path: "Show/Season 01/S01E01.mkv",
          library_path: lp
        }),
        build_media_file(%{
          id: "file-2",
          relative_path: "Show/Season 01/S01E02.mkv",
          library_path: lp
        }),
        build_media_file(%{
          id: "file-3",
          relative_path: "Show/Season 02/S02E01.mkv",
          library_path: lp
        })
      ]

      result = NfoWriter.detect_season_folders(files, lp)

      assert length(result) == 2
      assert {1, "/media/tv/Show/Season 01"} in result
      assert {2, "/media/tv/Show/Season 02"} in result
    end

    test "returns empty list when no season folders" do
      lp = build_library_path(%{path: "/media/tv"})

      files = [
        build_media_file(%{
          relative_path: "Show/S01E01.mkv",
          library_path: lp
        })
      ]

      assert NfoWriter.detect_season_folders(files, lp) == []
    end
  end

  describe "write_for_media_item/2" do
    test "skips writing when metadata is nil" do
      media_item = build_media_item(%{metadata: nil})
      lp = build_library_path()

      assert :ok = NfoWriter.write_for_media_item(media_item, lp)
    end

    test "skips writing when no media files" do
      media_item = build_media_item(%{metadata: build_metadata(), media_files: []})
      lp = build_library_path()

      assert :ok = NfoWriter.write_for_media_item(media_item, lp)
    end

    @tag :tmp_dir
    test "writes movie NFO files", %{tmp_dir: tmp_dir} do
      lp = build_library_path(%{path: tmp_dir})

      # Create the directory structure
      movie_dir = Path.join(tmp_dir, "The Matrix (1999)")
      File.mkdir_p!(movie_dir)
      movie_file = Path.join(movie_dir, "The Matrix (1999).mkv")
      File.write!(movie_file, "fake video")

      media_file =
        build_media_file(%{
          relative_path: "The Matrix (1999)/The Matrix (1999).mkv",
          library_path: lp,
          library_path_id: lp.id
        })

      media_item =
        build_media_item(%{
          type: "movie",
          tmdb_id: 603,
          metadata: build_metadata(),
          media_files: [media_file]
        })

      assert :ok = NfoWriter.write_for_media_item(media_item, lp)

      nfo_path = Path.join(movie_dir, "The Matrix (1999).nfo")
      assert File.exists?(nfo_path)
      content = File.read!(nfo_path)
      assert content =~ "<movie>"
      assert content =~ "<title>The Matrix</title>"
    end

    @tag :tmp_dir
    test "writes TV show NFO files", %{tmp_dir: tmp_dir} do
      lp = build_library_path(%{path: tmp_dir})

      # Create directory structure
      show_dir = Path.join(tmp_dir, "Breaking Bad")
      season_dir = Path.join(show_dir, "Season 01")
      File.mkdir_p!(season_dir)
      ep_file = Path.join(season_dir, "S01E01.mkv")
      File.write!(ep_file, "fake video")

      episode = build_episode(%{id: "ep-1", season_number: 1, episode_number: 1})

      media_file =
        build_media_file(%{
          relative_path: "Breaking Bad/Season 01/S01E01.mkv",
          library_path: lp,
          library_path_id: lp.id,
          episode_id: "ep-1"
        })

      metadata =
        build_metadata(%{
          media_type: :tv_show,
          title: "Breaking Bad",
          seasons: [%SeasonInfo{season_number: 1, name: "Season 1", overview: "The start."}]
        })

      media_item =
        build_media_item(%{
          type: "tv_show",
          tmdb_id: 1396,
          tvdb_id: 81189,
          metadata: metadata,
          media_files: [media_file],
          episodes: [episode]
        })

      assert :ok = NfoWriter.write_for_media_item(media_item, lp)

      # Check tvshow.nfo
      tvshow_nfo = Path.join(show_dir, "tvshow.nfo")
      assert File.exists?(tvshow_nfo)
      assert File.read!(tvshow_nfo) =~ "<tvshow>"

      # Check season.nfo
      season_nfo = Path.join(season_dir, "season.nfo")
      assert File.exists?(season_nfo)
      assert File.read!(season_nfo) =~ "<season>"

      # Check episode NFO
      ep_nfo = Path.join(season_dir, "S01E01.nfo")
      assert File.exists?(ep_nfo)
      assert File.read!(ep_nfo) =~ "<episodedetails>"
    end

    test "filters out trashed media files" do
      lp = build_library_path()

      trashed_file =
        build_media_file(%{
          trashed_at: DateTime.utc_now(),
          library_path: lp,
          library_path_id: lp.id
        })

      media_item =
        build_media_item(%{
          metadata: build_metadata(),
          media_files: [trashed_file]
        })

      # Should not write anything (no active files)
      assert :ok = NfoWriter.write_for_media_item(media_item, lp)
    end

    test "filters media files not in the target library path" do
      lp = build_library_path(%{id: "lp-1"})
      other_lp = build_library_path(%{id: "lp-2", path: "/other"})

      file_in_other =
        build_media_file(%{
          library_path: other_lp,
          library_path_id: "lp-2"
        })

      media_item =
        build_media_item(%{
          metadata: build_metadata(),
          media_files: [file_in_other]
        })

      # Should not write anything (file not in target library path)
      assert :ok = NfoWriter.write_for_media_item(media_item, lp)
    end
  end
end
