apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-db-data
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible-db
    app.kubernetes.io/component: analytics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-events-db-data
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible-events-db
    app.kubernetes.io/component: analytics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-data
  namespace: plausible
  labels:
    app.kubernetes.io/name: plausible
    app.kubernetes.io/component: analytics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
